### ISSUE TITLE
Generate quizzes (QR codes)

### ISSUE THREAD

**Issue by eugeniu-u** [TUM-FAF/Thesis-FAF-111-Ungureanu-Eugeniu#2]

**Comment by bumbu** [comment]
You can close issues from commit messages by setting your commit message as `Generate quizzes and add them to PDF. Close #2`. This will link that commit to this issue and will close the issue.

https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by eugeniu-u** [comment]
Wow. Thanks. Good to know :)
