### ISSUE TITLE
Error when trying to generate a quiz

### ISSUE THREAD

**Issue by bumbu** [TUM-FAF/Thesis-FAF-111-Ungureanu-Eugeniu#8]
When I try generating a quiz (using old and newly created quizes).

```
NoMethodError in GeneratedQuizzesController#create
undefined method `squares_xy=' for #<Copy:0x007fdcebb6afb0>

Extracted source (around line #19):       
      set_questions(copy)   
      start_new_page
      copy.squares_xy = @square_coordinates
      copy.save
    end
  end

Rails.root: /Users/bumbu/Development/Web/Thesis-FAF-111-Ungureanu-Eugeniu

Application Trace | Framework Trace | Full Trace
app/pdfs/quiz_pdf.rb:19:in `block in quiz_questions'
app/pdfs/quiz_pdf.rb:12:in `quiz_questions'
app/pdfs/quiz_pdf.rb:8:in `initialize'
app/controllers/generated_quizzes_controller.rb:20:in `new'
app/controllers/generated_quizzes_controller.rb:20:in `create'
Request

Parameters:

{"utf8"=>"✓",
 "_method"=>"create",
 "authenticity_token"=>"xTVFqurjOHF241NSQvhKOyBuWVbltLDp81izgAKW4hzf3oYXL0pnAwoRWvrIu3z+ud3OUEJrkQQvv+8z5oWbpA==",
 "generated_quiz"=>{"quiz_id"=>"4",
 "course_id"=>"2",
 "copies_nr"=>"1",
 "random_opt"=>"0",
 "student_group_ids"=>[""],
 "questions_nr"=>"1",
 "versions_nr"=>"1",
 "question_groups_nrs"=>{"8"=>"1"}},
 "commit"=>"Generate"}
```

**Comment by eugeniu-u** [comment]
This should fix it: `rake db:rollback STEP=3 && rake db:migrate`
It gives the error because I changed a migration directly.

**Comment by bumbu** [comment]
That worked. But why simple `rake db:migrate` didn't work?

**Comment by eugeniu-u** [comment]
The 'copies' table has been already migrated in your project, and `rake` doesn't see it as a candidate for migration, even if you change it manually.

The schema containing all the tables' structures must be partially deconstructed, by running `rake db:rollback`, so it doesn't contain the table which should have the new field.

Then `rake db:migrate` works normally

**Comment by bumbu** [comment]
From what I know you can migrate not only table creation/deletion but also table structure change and data alteration. Some of these migrations can't be automatically created so you have to write them by hand, but it is still possible.

**Comment by eugeniu-u** [comment]
I know about that. But they are mainly used in deployment, when you don't want to mess up the database. In ~~production~~ development though, I prefer to do it this way, so I don't write a migration for every minor change.

**Comment by bumbu** [comment]
It is a good habit to do it in both development and production. And it gets more useful when you're developing not alone. Also full migrations are useful when you want to reverse some changes.

p.s.
- _deployment_ - normally called _deploy_, is the process of deploying the code into development/production servers (pre-live, live versions)
- _development_ - branch/server that contains latest changes (often is ahead of production). 
- _production_ - branch/server that contains latest stable version that is published/deployed to live server/usable by public audiences

**Comment by eugeniu-u** [comment]
I know what these terms mean. :D It was a mistake when I wrote 'production'
